<a href="https://colab.research.google.com/github/sudsali/DSBDA/blob/main/Heart_Dataset_Classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Sudhanshu Sali  
### TEIT 
### 9059  
### DSBDA Assignment 2B

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df = pd.read_csv('/content/sample_data/Heart.csv')
df

Unnamed: 0   Age  Sex     ChestPain  RestBP   Chol  Fbs  RestECG  MaxHR  \
0             1  63.0    1       typical   145.0  233.0  1.0      2.0  150.0   
1             2  67.0    1  asymptomatic   160.0  286.0  0.0      2.0  108.0   
2             3  67.0    1  asymptomatic   120.0  229.0  0.0      2.0  129.0   
3             4  37.0    1    nonanginal   130.0  250.0  0.0      0.0  187.0   
4             5  41.0    0    nontypical   130.0  204.0  0.0      2.0  172.0   
..          ...   ...  ...           ...     ...    ...  ...      ...    ...   
298         299  45.0    1       typical   110.0    NaN  0.0      NaN  132.0   
299         300  68.0    1  asymptomatic   144.0  193.0  1.0      0.0    NaN   
300         301  57.0    1  asymptomatic   130.0  131.0  0.0      0.0  115.0   
301         302  57.0    0    nontypical   130.0  236.0  0.0      2.0  174.0   
302         303  38.0    1    nonanginal     NaN  175.0  0.0      0.0  173.0   

     ExAng  Oldpeak  Slope   Ca        Thal  AHD  
0      0.0      2.3    3.0  0.0       fixed   No  
1      1.0      1.5    2.0  3.0      normal  Yes  
2      1.0      2.6    2.0  2.0  reversable  Yes  
3      0.0      3.5    3.0  0.0      normal   No  
4      0.0      1.4    1.0  0.0      normal   No  
..     ...      ...    ...  ...         ...  ...  
298    0.0      1.2    2.0  0.0  reversable  Yes  
299    0.0      3.4    2.0  2.0  reversable  Yes  
300    1.0      1.2    2.0  1.0  reversable  Yes  
301    0.0      0.0    2.0  1.0      normal  Yes  
302    0.0      0.0    1.0  NaN      normal   No  

[303 rows x 15 columns]

In [ ]:
df.shape

(303, 15)

In [ ]:
df.describe()

Unnamed: 0         Age         Sex      RestBP        Chol         Fbs  \
count  303.000000  302.000000  303.000000  299.000000  301.000000  301.000000   
mean   152.000000   54.476821    0.679868  131.571906  246.504983    0.146179   
std     87.612784    9.029545    0.467299   17.679777   51.889666    0.353874   
min      1.000000   29.000000    0.000000   94.000000  126.000000    0.000000   
25%     76.500000   48.000000    0.000000  120.000000  211.000000    0.000000   
50%    152.000000   56.000000    1.000000  130.000000  240.000000    0.000000   
75%    227.500000   61.000000    1.000000  140.000000  275.000000    0.000000   
max    303.000000   77.000000    1.000000  200.000000  564.000000    1.000000   

          RestECG       MaxHR       ExAng     Oldpeak       Slope          Ca  
count  301.000000  302.000000  302.000000  302.000000  301.000000  298.000000  
mean     0.996678  149.635762    0.324503    1.043046    1.598007    0.667785  
std      0.994982   22.907581    0.468966    1.161452    0.617411    0.935839  
min      0.000000   71.000000    0.000000    0.000000    1.000000    0.000000  
25%      0.000000  133.250000    0.000000    0.000000    1.000000    0.000000  
50%      1.000000  153.000000    0.000000    0.800000    2.000000    0.000000  
75%      2.000000  166.000000    1.000000    1.600000    2.000000    1.000000  
max      2.000000  202.000000    1.000000    6.200000    3.000000    3.000000

In [ ]:
df.dtypes

Unnamed: 0      int64
Age           float64
Sex             int64
ChestPain      object
RestBP        float64
Chol          float64
Fbs           float64
RestECG       float64
MaxHR         float64
ExAng         float64
Oldpeak       float64
Slope         float64
Ca            float64
Thal           object
AHD            object
dtype: object

## Data cleaning

In [ ]:
df.isnull().sum()

Unnamed: 0    0
Age           1
Sex           0
ChestPain     0
RestBP        4
Chol          2
Fbs           2
RestECG       2
MaxHR         1
ExAng         1
Oldpeak       1
Slope         2
Ca            5
Thal          2
AHD           0
dtype: int64

In [ ]:
df.drop('Unnamed: 0',inplace=True,axis=1)

In [ ]:
df

Age  Sex     ChestPain  RestBP   Chol  Fbs  RestECG  MaxHR  ExAng  \
0    63.0    1       typical   145.0  233.0  1.0      2.0  150.0    0.0   
1    67.0    1  asymptomatic   160.0  286.0  0.0      2.0  108.0    1.0   
2    67.0    1  asymptomatic   120.0  229.0  0.0      2.0  129.0    1.0   
3    37.0    1    nonanginal   130.0  250.0  0.0      0.0  187.0    0.0   
4    41.0    0    nontypical   130.0  204.0  0.0      2.0  172.0    0.0   
..    ...  ...           ...     ...    ...  ...      ...    ...    ...   
298  45.0    1       typical   110.0    NaN  0.0      NaN  132.0    0.0   
299  68.0    1  asymptomatic   144.0  193.0  1.0      0.0    NaN    0.0   
300  57.0    1  asymptomatic   130.0  131.0  0.0      0.0  115.0    1.0   
301  57.0    0    nontypical   130.0  236.0  0.0      2.0  174.0    0.0   
302  38.0    1    nonanginal     NaN  175.0  0.0      0.0  173.0    0.0   

     Oldpeak  Slope   Ca        Thal  AHD  
0        2.3    3.0  0.0       fixed   No  
1        1.5    2.0  3.0      normal  Yes  
2        2.6    2.0  2.0  reversable  Yes  
3        3.5    3.0  0.0      normal   No  
4        1.4    1.0  0.0      normal   No  
..       ...    ...  ...         ...  ...  
298      1.2    2.0  0.0  reversable  Yes  
299      3.4    2.0  2.0  reversable  Yes  
300      1.2    2.0  1.0  reversable  Yes  
301      0.0    2.0  1.0      normal  Yes  
302      0.0    1.0  NaN      normal   No  

[303 rows x 14 columns]

In [ ]:
df['Age'] = df['Age'].fillna(df['Age'].mean())
df['RestBP'] = df['RestBP'].fillna(df['RestBP'].mean())

In [ ]:
df['Ca'] = df['Ca'].fillna(1).astype(int)
df['Ca'].values

array([0, 3, 2, 0, 0, 0, 2, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 2, 2, 0, 0, 0, 0, 0, 2, 2, 0, 0, 0, 0, 0, 1, 1, 0, 3, 0, 2, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 3, 0, 1, 2,
       0, 0, 0, 0, 0, 2, 2, 2, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 3, 3, 0, 0, 1, 1, 2, 1, 0, 0, 0, 1, 1, 3, 0, 1, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 3, 1, 2, 3, 0, 0, 1, 0, 2, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 1, 0, 0, 0, 1,
       1, 3, 0, 2, 2, 1, 0, 3, 0, 0, 2, 0, 1, 1, 0, 0, 1, 0, 0, 0, 2, 1,
       3, 1, 1, 3, 0, 2, 2, 0, 0, 2, 0, 3, 1, 3, 0, 3, 1, 3, 0, 2, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 3, 2, 0, 0, 0, 0, 0, 0, 2, 1, 0, 0, 0, 2, 0,
       0, 0, 0, 2, 2, 0, 0, 1, 1, 1, 0, 0, 3, 1, 1, 2, 0, 0, 0, 0, 0, 0,
       0, 2, 0, 0, 1, 1, 2, 0, 0, 1, 1, 0, 0, 0, 2, 0, 0, 0, 1, 2, 0, 0,
       1, 0, 0, 1, 0, 0, 1, 0, 2, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 3,
       2, 1, 0, 0, 0, 0, 0, 2, 0, 0, 2, 0, 0, 2, 1,

In [ ]:
df.dropna(inplace=True)
df.isnull().sum()

Age          0
Sex          0
ChestPain    0
RestBP       0
Chol         0
Fbs          0
RestECG      0
MaxHR        0
ExAng        0
Oldpeak      0
Slope        0
Ca           0
Thal         0
AHD          0
dtype: int64

In [ ]:
df['AHD']=df['AHD'].replace({'Yes':1, 'No':0})
df.head()

Age  Sex     ChestPain  RestBP   Chol  Fbs  RestECG  MaxHR  ExAng  \
0  63.0    1       typical   145.0  233.0  1.0      2.0  150.0    0.0   
1  67.0    1  asymptomatic   160.0  286.0  0.0      2.0  108.0    1.0   
2  67.0    1  asymptomatic   120.0  229.0  0.0      2.0  129.0    1.0   
3  37.0    1    nonanginal   130.0  250.0  0.0      0.0  187.0    0.0   
4  41.0    0    nontypical   130.0  204.0  0.0      2.0  172.0    0.0   

   Oldpeak  Slope  Ca        Thal  AHD  
0      2.3    3.0   0       fixed    0  
1      1.5    2.0   3      normal    1  
2      2.6    2.0   2  reversable    1  
3      3.5    3.0   0      normal    0  
4      1.4    1.0   0      normal    0

## Data Transformation

In [ ]:
df['ChestPain'].nunique()

4

In [ ]:
df['Thal'].nunique()

3

### Splitting dataset into training and testing

In [ ]:
from sklearn.model_selection import train_test_split
y = df.pop('AHD')
y = np.array(y)

In [ ]:
X = df
X

Age  Sex     ChestPain      RestBP   Chol  Fbs  RestECG  MaxHR  ExAng  \
0    63.0    1       typical  145.000000  233.0  1.0      2.0  150.0    0.0   
1    67.0    1  asymptomatic  160.000000  286.0  0.0      2.0  108.0    1.0   
2    67.0    1  asymptomatic  120.000000  229.0  0.0      2.0  129.0    1.0   
3    37.0    1    nonanginal  130.000000  250.0  0.0      0.0  187.0    0.0   
4    41.0    0    nontypical  130.000000  204.0  0.0      2.0  172.0    0.0   
..    ...  ...           ...         ...    ...  ...      ...    ...    ...   
295  41.0    1    nontypical  120.000000  157.0  0.0      0.0  182.0    0.0   
296  59.0    1  asymptomatic  164.000000  176.0  1.0      2.0   90.0    0.0   
300  57.0    1  asymptomatic  130.000000  131.0  0.0      0.0  115.0    1.0   
301  57.0    0    nontypical  130.000000  236.0  0.0      2.0  174.0    0.0   
302  38.0    1    nonanginal  131.571906  175.0  0.0      0.0  173.0    0.0   

     Oldpeak  Slope  Ca        Thal  
0        2.3    3.0   0       fixed  
1        1.5    2.0   3      normal  
2        2.6    2.0   2  reversable  
3        3.5    3.0   0      normal  
4        1.4    1.0   0      normal  
..       ...    ...  ..         ...  
295      0.0    1.0   0      normal  
296      1.0    2.0   2       fixed  
300      1.2    2.0   1  reversable  
301      0.0    2.0   1      normal  
302      0.0    1.0   1      normal  

[293 rows x 13 columns]

In [ ]:
type(X)

pandas.core.frame.DataFrame

In [ ]:
type(y)

numpy.ndarray

### Encoding independent features using OneHotEncoder

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [2,12])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [ ]:
print(X)

[[0.  0.  0.  ... 2.3 3.  0. ]
 [1.  0.  0.  ... 1.5 2.  3. ]
 [1.  0.  0.  ... 2.6 2.  2. ]
 ...
 [1.  0.  0.  ... 1.2 2.  1. ]
 [0.  0.  1.  ... 0.  2.  1. ]
 [0.  1.  0.  ... 0.  1.  1. ]]


In [ ]:
print(X[0])

[  0.    0.    0.    1.    1.    0.    0.   63.    1.  145.  233.    1.
   2.  150.    0.    2.3   3.    0. ]


In [ ]:
type(X)

numpy.ndarray

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.7)
print("X_train", X_train.shape)
print("X_test", X_test.shape)
print("y_train", y_train.shape)
print("y_test", y_test.shape)

X_train (205, 18)
X_test (88, 18)
y_train (205,)
y_test (88,)


## Logistic Regression Model

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
classifier = LogisticRegression()
classifier.fit(X_train,y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


LogisticRegression()

In [ ]:
y_pred = classifier.predict(X_test)

In [ ]:
print(np.concatenate((y_pred.reshape(-1,1),y_test.reshape(-1,1)),1))

[[0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 0]
 [1 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [1 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 0]
 [1 1]
 [0 1]
 [1 1]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 1]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [1 1]
 [0 1]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]]


### Confusion Matrix

In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score
cf_matrix = confusion_matrix(y_test,y_pred)
print(cf_matrix)

[[39  7]
 [ 8 34]]


In [ ]:
print('Accuracy of the model:',accuracy_score(y_test, y_pred))

Accuracy of the model: 0.8295454545454546


In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.83      0.85      0.84        46
           1       0.83      0.81      0.82        42

    accuracy                           0.83        88
   macro avg       0.83      0.83      0.83        88
weighted avg       0.83      0.83      0.83        88

